version: '3'
services:
  mongo:
    container_name: mongodb-container
    image: mongo:4
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '17017:27017'
  api:
    container_name: api-container
    restart: always
    image: node:10
    working_dir: /usr/src/responde-ai-backend
    command: bash -c "npm install --only=prod && npm run debug"
    volumes:
      - ./dist/:/usr/src/responde-ai-backend/dist/
      - ./package.json:/usr/src/responde-ai-backend/package.json
      - ./responde-ai-cloud-firebase-adminsdk-jw7h4-5eb2cc0c57.json:/usr/src/responde-ai-backend/responde-ai-cloud-firebase-adminsdk-jw7h4-5eb2cc0c57.json
    ports:
      - '3030:3030'
      - '9222:9222'
    links:
      - mongo
